import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Banner */}
        <div className="bg-primary text-black w-full py-6 fixed top-0 left-0 border-b border-gray z-10">
          <h1 className="text-5xl font-bold text-center">
            <span className="font-extrabold">625</span>
            <span className="font-normal">Tutor</span>
          </h1>
        </div>
        <div className="mt-24">
          {children}
        </div>
      </body>
    </html>
  );
}
